package com.delifery.delifery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExpressDeliveryInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExpressDeliveryInfo() {
    }




}